# Generated by Django 6.0.2 on 2026-02-19 13:15

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Pavadinimas')),
                ('code', models.CharField(max_length=10, verbose_name='Prekės kodas')),
                ('category', models.CharField(choices=[('1', 'Motociklai'), ('2', 'Atsarginės dalys'), ('3', 'Apranga'), ('4', 'Aksesuarai'), ('5', 'Padangos')], max_length=1, verbose_name='Kategorija')),
                ('manufacturer', models.CharField(verbose_name='Gamintojas')),
                ('size', models.CharField(blank=True, choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL')], max_length=1, null=True, verbose_name='Dydis')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Kiekis sandėlyje/pas tiekėją')),
                ('stocked', models.BooleanField(default=True, verbose_name='Ar yra sandelyje?')),
                ('definition', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Aprašymas')),
                ('new_product', models.BooleanField(default=False, verbose_name='Ar prekė nauja')),
                ('rrp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Rekom. mažmeninė kaina')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Pardavimo kaina')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='product_covers', verbose_name='Nuotrauka')),
            ],
            options={
                'verbose_name': 'Prekė',
                'verbose_name_plural': 'Prekės',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='Užsakymo pateikimo data')),
                ('status', models.CharField(choices=[('1', 'Pateiktas'), ('2', 'Surenkamas'), ('3', 'Paruoštas'), ('4', 'Perduotas pristatymui'), ('5', 'Vėluoja'), ('6', 'Užbaigtas'), ('7', 'Atšauktas')], default='1', max_length=1, verbose_name='Statusas')),
                ('due_date', models.DateField(verbose_name='Užsakymo užbaigimo data')),
                ('client', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Klientas')),
            ],
            options={
                'verbose_name': 'Užsakymas',
                'verbose_name_plural': 'Užsakymai',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Pavadinimas')),
                ('content', tinymce.models.HTMLField(verbose_name='Tūrinys')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Įrašas sukūrtas')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='posts_covers', verbose_name='Viršelis')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Autorius')),
            ],
            options={
                'verbose_name': 'Įrašas',
                'verbose_name_plural': 'Įrašai',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Komentaras')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Komentaro data')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Komentatorius')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='motoshop.post', verbose_name='Įrašas')),
            ],
            options={
                'verbose_name': 'Komentaras',
                'verbose_name_plural': 'Komentarai',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Kiekis')),
                ('order', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ol', to='motoshop.order', verbose_name='Užsakymas')),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ol', to='motoshop.product', verbose_name='Produktas')),
            ],
            options={
                'verbose_name': 'Užsakymo eilutė',
                'verbose_name_plural': 'žsakymo eilutės',
            },
        ),
    ]
