# Generated by Django 6.0.2 on 2026-02-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0002_product_order_post_comment_orderline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutės'},
        ),
    ]
