# Generated by Django 6.0.2 on 2026-02-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0003_alter_orderline_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Vartotojas', 'verbose_name_plural': 'Vartotojai'},
        ),
    ]
