# Generated by Django 6.0.2 on 2026-02-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('1', 'Motociklai'), ('2', 'Atsarginės dalys'), ('3', 'Apranga'), ('4', 'Aksesuarai')], max_length=1, verbose_name='Kategorija'),
        ),
    ]
