# Generated by Django 6.0.2 on 2026-02-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics', verbose_name='Nuotrauka'),
        ),
    ]
