# Generated by Django 6.0.2 on 2026-02-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0006_alter_customuser_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Kategorija')),
            ],
        ),
        migrations.AddField(
            model_name='orderline',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motoshop.productcategory', verbose_name='Prekės kategorija'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='motoshop.productcategory', verbose_name='Prekės kategorija'),
        ),
    ]
