# Generated by Django 6.0.2 on 2026-02-24 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0007_productcategory_orderline_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategorija', 'verbose_name_plural': 'Kategorijos'},
        ),
    ]
