# Generated by Django 6.0.2 on 2026-02-24 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0008_alter_productcategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(db_constraint=False, limit_choices_to={'product_category': 1}, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ol', to='motoshop.product', verbose_name='Produktas'),
        ),
    ]
