# Generated by Django 6.0.2 on 2026-02-24 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0009_alter_orderline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ol', to='motoshop.product', verbose_name='Produktas'),
        ),
    ]
