# Generated by Django 6.0.2 on 2026-02-25 10:05

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0010_alter_orderline_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderline',
            name='product',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product_category', chained_model_field='product_category', db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ol', to='motoshop.product', verbose_name='Produktas'),
        ),
    ]
