# Generated by Django 6.0.2 on 2026-02-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motoshop', '0011_alter_orderline_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk'], 'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
    ]
